pip install datetime
pip install pyodbc
pip install sqlalchemy
pip install lxml
pip install zipfile36
pip install py_vollib
pip install qtpy==1.9.0
pip install qdarkstyle==2.8.1
pip install pyqt5
pip install shapely
pip install dill
pip install numpy==1.20.3
pip install numba
pip install pandas
pip install requests
pip install websocket_client==0.57.0
pip install python-socketio==4.6.0
pip install python-engineio==3.14.2
pip install datatable==0.11.0
pip install playsound
pip install gtts
pip install beepy
pip install qtwidgets
pip install py_vollib
pip install cython
pip install git+https://github.com/System233/lzo